# Generated by Django 3.1.6 on 2021-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('expansion', models.CharField(max_length=20)),
                ('notes_1', models.CharField(max_length=50, null=True)),
                ('notes_2', models.CharField(max_length=500, null=True)),
                ('requirements', models.CharField(max_length=50, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('url_info', models.CharField(max_length=100, null=True)),
                ('url_wowhead', models.CharField(max_length=100, null=True)),
                ('image_mini', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=100, null=True)),
                ('url_img', models.CharField(max_length=100, null=True)),
                ('url_img_min', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
