# Generated by Django 3.1.6 on 2021-03-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('expansion', models.CharField(max_length=20)),
                ('notes_1', models.CharField(max_length=50)),
                ('notes_2', models.CharField(max_length=500)),
                ('requirements', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('url_info', models.CharField(max_length=100)),
                ('url_wowhead', models.CharField(max_length=100)),
                ('image_mini', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
