# Generated by Django 3.1.6 on 2021-03-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountsHunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mount',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mount',
            name='image_mini',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mount',
            name='notes_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mount',
            name='notes_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mount',
            name='requirements',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mount',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mount',
            name='url_info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mount',
            name='url_wowhead',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
